### ISSUE TITLE
Ambiguous statement of 2DS

### ISSUE THREAD

**Issue by ZacksH** [hacks-guide/Guide_3DS#1620]
The last line in the home page:

> The 2DS is essentially identical to the Old 3DS in terms of software, and that any steps which say “Old 3DS” also apply to 2DS.

It is confusing for me if new 2DS XL should also follow the steps of Old 3DS?

So is that better to say ```2DS -> old 3DS``` and ```new 2DS -> new 3DS```?

**Comment by zacchi4k** [comment]
Yes if the *NEW* 2DS XL is part of the NEW 3DS line
