### ISSUE TITLE
https://3ds.hacks.guide/rss.xml some of the torrents are dead

### ISSUE THREAD

**Issue by catfatwm** [hacks-guide/Guide_3DS#1623]
i would like to contribute by perma seeding all listed torrents in this guide with my seedbox, however i have to manually add each one by hand. ive gone down the list about 10 or so down and none of them seed to have any peers/seeds/leechers or the magnet uri just isnt working for me. is there an easier way i can perma seed more things than just the frogtool?

**Comment by Plailect** [comment]
Everything in the RSS should have seeders as multiple seedboxes are pointed at it. All you have to do to seed them yourself is get a client that supports RSS feeds, then add the RSS URL to it which will add all the torrents automatically. If you are not seeing any seeds, it is likely a networking issue on your end.

**Comment by james-d-elliott** [comment]
I use Deluge with the RSS2 plugin. Works fine. You can only configure it with the GTK UI though, the Web UI doesn't support it. So if the seedbox is in the cloud you'll have to open the daemon port to the world and add some firewall rules to protect it.
