### ISSUE TITLE
Requests for the frogminer guide

### ISSUE THREAD

**Issue by MehdiKhelfi** [hacks-guide/Guide_3DS#1624]
Hi , that was just to ask you to add 2 things to your frogminer hack guide please :

1. Put a warning to not delete 484E4441.bin cuz some people (like me) deletes the file thinking it's not useful .

2. If someone deleted the 484E4441.bin , it's recoverable by downloading the ds download play cia , I know you won't put the link or something because it's copyrighted but you can just tell that tey can search a little bit on the internet and they'll find (zoogie told the solution on the 3dshacks subreddit) 

hoping that will help people. thx

**Comment by zacchi4k** [comment]
The DS Download Play is linked in the guide as part of the steps for repairing DS Mode in the troubleshooting guide. An alternative (but far less convenient) way is to delete the DS Download Play title from FBI and performing a system update to restore it

**Comment by MechanicalDragon0687** [comment]
the frogminer guide currently has you use the file as necessary in finalizing setup. prior to finishing the guide, you are never told to delete anything. warning someone not to delete a file from the SD card in the middle of the guide seems unnecessary.

**Comment by Plailect** [comment]
I agree with @MechanicalDragon0687, it would be quite cluttered if the guide warned every single time you *should not* do something. There's many ways to break your system by not following instructions, so just do exactly as the guide instructs and everything will be fine.
