### ISSUE TITLE
No active seeds for one of the rss files

### ISSUE THREAD

**Issue by 16BitWonder** [hacks-guide/Guide_3DS#1638]
I have yet to come across any seeds when attempting to grab "R4i-SDHC_B9S-Flashrom.zip" for a couple weeks now. I can see about 130 peers connected and none from what I've seen have any % of it.

In my client it's stuck "downloading metadata", which normally I would assume there's something wrong on my end from that error, but every other file has retrieved metadata and downloaded just fine from the rss feed.

**Comment by Plailect** [comment]
I don't have the data for that unfortunately. I suppose a new one will need to be created if this is still an issue.

**Comment by TurdPooCharger** [comment]
There is another another torrent named **R4i-SDHC_B9S-Flashrom.zip**. 

39EF29B9520DB11CAFD28399E2D79EE52C7A98E6

**Comment by Plailect** [comment]
I believe that was an old version which would not work if restored to

**Comment by TurdPooCharger** [comment]
Since they're both made by **www.r4i-sdhc.com**, would the **R4i-SDHC B9S** happen to share the same flashrom as the **R4i-SDHC RTS**? Is there a chance the B9S model is just a relabeled RTS model?

**Comment by TurdPooCharger** [comment]
http://www.r4i-sdhc.com/B9SSector.asp

???
 B9S Flasher V2.0 download (Flashing B9S to NDS flashcart or reversely)

**Comment by 16BitWonder** [comment]
The file is no longer stuck retrieving metadata, but I have still yet to come across peers that have any of the file.

In case it's necessary, the hash is e69d9e3a759affd75ad8360e360a07562afad317.

**Comment by 16BitWonder** [comment]
Little update to this, I've found the flashrom and compressed it as the others were.

Rechecking the content has it passing 99.2%, even with the full zip.
It does appear to be seeding now so at least it's being distributed again.
Though I'm not sure if those downloading it are able to open the archive.
Unless someone with the full original file begins seeding the last .8% it may never complete for folks.

**Comment by TurdPooCharger** [comment]
The first 0x8000 bytes of that ZIP are filled with 00. Can't open or repair the archive. :(

**Comment by 16BitWonder** [comment]
That's really strange, the zip I'm seeding has that space filled in just fine, but moving it elsewhere and downloading what is currently in the pool definitely shows that section is zero'd out for everyone else.
(Mayhaps this is the .8% section not matching the original file?)

I tested from a couple different clients and attempted different compression settings and none seem to want to include the first 0x8000 bytes.

I doubt there's much else that can be done at this point, but if anyone else is interested in checking it out, I got the flashrom from [here](http://www.r4i-sdhc.com/down/b9s/B9S%20flasher%20V2.0.zip).
Renaming the flashrom to r4isdhc-backup.bin and then compressing normally or store is what produced the 99.2% archive.

**Comment by TurdPooCharger** [comment]
The **B9S flasher v2.0.zip** contains `r4i-sdhc.bin` , which has the size: 4.00 MB and CRC32 hash: **D482EA1D**.

***

That other torrent with the same name but hash info:

**R4i-SDHC_B9S-Flashrom.zip**
39EF29B9520DB11CAFD28399E2D79EE52C7A98E6

, has `backup.bin` with the same size and CRC32 hash.

***

That means the torrent in question with the other hash info:

**R4i-SDHC_B9S-Flashrom.zip**
E69D9E3A759AFFD75AD8360E360A07562AFAD317

, has the same flashrom albeit named as `r4isdhc-backup.bin`.

***

Of the 129 (32.0 KiB) pieces, the last two chunks fail checksum due to the ZIP containers' slight difference in metadata (ie, ~ created date).
