### ISSUE TITLE
TWL_FIRM cias are outdated.

### ISSUE THREAD

**Issue by TurdPooCharger** [hacks-guide/Guide_3DS#1644]
In the **Troubleshooting** section, these are no longer compatible with firmware 11.9.0-42X.
- New_3DS TWL_FIRM - v9936.cia
- Old_3DS TWL_FIRM - v8817.cia

The latest versions are:
- **n3DS:** 0004013820000102 v10962 
- **o3DS:** 0004013800000102 v10864

**Comment by aspargas2** [comment]
The TWL fixing section has been completely changed to not involve torrenting the cias and rather forcing the 3ds to redownload the 5 TWL titles via an update, so I think this can be closed.
