### ISSUE TITLE
homebrew won't load .dsx files

### ISSUE THREAD

**Issue by REINFORCEDBEAR4** [hacks-guide/Guide_3DS#1696]
i don't know if this is the place to ask but i need help.
i have successfully installed everything and all runs smoothly so when i open homebrew from the home menu it will load fine and i can run applications except the ones that i have tried to put on recently the application appears but when i try to load it the screen goes black and that's it i have the dsx file there and an sdmh file but am i missing something?

**Comment by Plailect** [comment]
This is not a support forum. Try the discord or reddit.
