### ISSUE TITLE
Add a disclaimer when the translated guides are outdated

### ISSUE THREAD

**Issue by zacchi4k** [hacks-guide/Guide_3DS#1711]
When a major update for the guide comes out (for example, with BannerBomb3), it usually takes several weeks for the various translations to be completed and for those changes to be added to the site. This mean that when a major update comes out, many users will still be modding their consoles using obsolete and potentially non-working methods (this isn't the case for bb3/fredminer, but it could happen in the future).

My idea was to create a disclaimer and have it be translated in every language (either from Crowdin, from other, faster sources, or even from Google translate), so that when the English guide gets updated, the disclaimer could be put at the beginning of the translated guides in big letters (or even at the beginning of every page), telling users that the guide they're following is outdated, and instructing them in either following the English guide, wait for the new translation to be uploaded, or even follow a third party  guide instead

**Comment by lilyuwuu** [comment]
I'm not sure how/if this can be done with crowdin. :/ As is, if a new method is introduced then it'll just display the English version with maybe a few lines in the language until people translate it.

**Comment by lifehackerhansol** [comment]
This can't really be done with Crowdin, no.

The best alternative is to merge translations whenever there is a huge update.

**Comment by MechanicalDragon0687** [comment]
Would be nice but overall this is not feasible
