### ISSUE TITLE
Move the TWLFix troubleshooting steps to the Finalizing Setup page

### ISSUE THREAD

**Issue by RocketRobz** [hacks-guide/Guide_3DS#1714]
My guess is that the CTR transfers are what's causing TWL_FIRM to break.
With new users getting TWiLight Menu++, this bug seems to be more apparent.

**Comment by MechanicalDragon0687** [comment]
We have reproduced twl breakage by performing only a ctr transfer (multiple times).
It may not be the only thing that causes it, but it is one of the big things that does.

Adding a note to check twl to the finalizing setup page may make sense, it already exists in the troubleshooting section and as part of the current version installation guide (sans ntrboot)
