### ISSUE TITLE
R4iSDHC 20XX Time Bomb Update

### ISSUE THREAD

**Issue by agtbaskara** [hacks-guide/Guide_3DS#1715]
The R4iSDHC 20XX from www.r4isdhc.com now has updated to 4.0b kernel with a new timebomb in 2024, the website still showed 3.9b.

Source:
https://gbatemp.net/threads/r4isdhc-4-0b-released-kernel-is-now-expires-on-2024.522097/

**Comment by TurdPooCharger** [comment]
Maybe add link to YS Menu for flashcarts with time bombs.
- [RetroGameFan Updates/Releases](https://gbatemp.net/threads/retrogamefan-updates-releases.267243/)

**Comment by MechanicalDragon0687** [comment]
the concern for adding ysmenu to the list is that you may not be able to flash reliably on ysmenu and it is outside the scope of the guide to provide flashcart usage guides outside of ntrboot.
