### ISSUE TITLE
Some links in the Guide was unavailable

### ISSUE THREAD

**Issue by OasisAkari** [hacks-guide/Guide_3DS#1717]
Start in sometime, these links was unavailable in the [installing boot9strap (browser)](https://3ds.hacks.guide/installing-boot9strap-(browser)).

![Screenshot_2019-10-14-00-21-28-116_com microsoft emmx](https://user-images.githubusercontent.com/31803608/66718775-525e8f80-ee1a-11e9-8873-4b4b009842a2.jpg)

and in the [region changing](https://3ds.hacks.guide/region-changing), this link was move to another address.
![Screenshot_2019-10-14-00-22-40-474_com microsoft emmx](https://user-images.githubusercontent.com/31803608/66718878-5808a500-ee1b-11e9-94fc-aa67331621a3.jpg)

**Comment by aspargas2** [comment]
Fixed the link on the region changing guide in c0150bb. As far as I can tell, only the middle link of the three on the browser page is a 404; is this what you meant to indicate?

**Comment by OasisAkari** [comment]
The third link some time ago was indeed 404, thanks for fix it.
