### ISSUE TITLE
inefficient moving of files (b92 fredtool)

### ISSUE THREAD

**Issue by TheOriginalSeeGreatness** [hacks-guide/Guide_3DS#1732]
The issue is in section 1 steps 3-5 on https://3ds.hacks.guide/installing-boot9strap-(fredtool)
steps 4 and 5 should be swapped or step 5 should be added to step 3 because the source files for step 5 and step 3 are the same! plus they have the same destination! 
also step 5 (current) should be clarified more, where can I find boot.3dsx ? currently there is no information on where to find this file, but the file is actually from luma.zip

**Comment by aspargas2** [comment]
Fixed in commit ccbc863. Seems nobody ever got around to closing the issue.
