### ISSUE TITLE
Error in godmode9 guide

### ISSUE THREAD

**Issue by Liger0** [hacks-guide/Guide_3DS#1735]
At the italian version of the godmode9 guide, it's written to press R+B to search for titles at the "backup title" section, but it should be R+A.

https://3ds.hacks.guide/it_IT/godmode9-usage.html

**Comment by ihaveamac** [comment]
I think you mean R+A. Looks like it's been updated by now though.

**Comment by Liger0** [comment]
No, it's still written R+B, which is wrong.

**Comment by ihaveamac** [comment]
Oh whoops, looks like I misread it. It is still wrong.

**Comment by aspargas2** [comment]
This was fixed in commit 99e1cb5.
