### ISSUE TITLE
CTRTransfer images for CHN/KOR/TWN

### ISSUE THREAD

**Issue by ihaveamac** [hacks-guide/Guide_3DS#1738]
We should have these images prepared at some point.

- [ ] CHN
- [ ] KOR
- [ ] TWN

**Comment by TurdPooCharger** [comment]
These are all for the old 3DS series, right? I know from the other currently available ctrtransfer images that they're stripped of most console unique files like `LocalFriendCodeSeed_B`, `HWCAL0.dat`, `HWCAL1.dat`, and `movable.sed`.

Are the sought after donor ctrnand images require legitimate `SecureInfo_A` and `certs.db` from real native CHN, TWN, and KOR systems?

**Comment by kescherCode** [comment]
o3ds KOR has a torrent, however, it is unseeded and only has a few peers with 99.9% completion. magnet:?xt=urn:btih:71807D893C6D6FC9490BF4C013477D0F9E8052EA

**Comment by thenist** [comment]
I have a Korean CTR transfer 11.6.0-35K but i have no idea how to share this

**Comment by ItsPizzaTime1501** [comment]
@thenist The best way would probably be to join [Nintendo Homebrew](https://discord.gg/C29hYvh) on discord and mention that you have a KOR region ctrtransfer image

**Comment by lilyuwuu** [comment]
We actually have all ctrnand_full images on hand... just need to do something with them at some point.
