### ISSUE TITLE
Replace F3X for macOS

### ISSUE THREAD

**Issue by ihaveamac** [hacks-guide/Guide_3DS#1739]
F3X apparently does not work anymore and isn't maintained: https://github.com/AltraMayor/f3/issues/127

**Comment by TurdPooCharger** [comment]
No luck either with Wine HQ + H2testw.
- [Catalina and the future of Wine on Mac](https://forum.winehq.org/viewtopic.php?f=9&t=32590)

**Comment by MechanicalDragon0687** [comment]
Can one not just use F3 on Mac?

**Comment by TurdPooCharger** [comment]
Probably not. Compiling source code specifically for Linux can sometimes be a hit or miss on Unix/BSD/Macintosh. It also doesn't help that Apple has a long history with their products and closed ecosystem being as unwelcoming as possible to open source software.

I suppose most Mac users who are into 3DS homebrew and that sort of stuff would most likely also have Windows bootcamp if they needed to check their SD card by H2testw. Those who are macOS only users and are owners of the latest MacBook models could resort to live booting a Linux distro of their choice from a USB flashdrive and then running F3 in that session.

Someone who's a Mac user, can you check if there's a software that's comparable to H2testw/F3/F3X found on the Mac App Store?

**Comment by ihaveamac** [comment]
F3 does exist for Mac, homebrew provides it too. The problem then would be teaching users how to use it.

**Comment by ihaveamac** [comment]
F3's repo has steps for building on Mac too https://github.com/AltraMayor/f3

**Comment by TurdPooCharger** [comment]
Does F3 on Mac works exactly like on Linux where you run it from command line?

**Comment by ihaveamac** [comment]
Yes f3write and f3read work exactly the same.

**Comment by TurdPooCharger** [comment]
If I wrote a tutorial with screenshots on how to download, compile, and run f3write & f3read on [Manjaro/Ubuntu/Mint] Linux, would that example be similar enough as a stand-in replacement for [F3X (Mac)](https://3ds.hacks.guide/f3x-(mac))?

I have a laptop that's Hackintosh compatible if we're aiming to capture authentic macOS desktop environment for those pictures but rather not go down that route.

**Comment by ihaveamac** [comment]
Probably, just without the compiling part since most users won't need to do that.

**Comment by TurdPooCharger** [comment]
I couldn't think of improvements to the written tutorial in the [F3 (Linux)](https://3ds.hacks.guide/f3-(linux)), except adding an example image as a visual aid.

Is this sufficient and generic enough for both Linux and Mac?

![F3_Terminal](https://user-images.githubusercontent.com/35666439/84602783-c5138500-ae57-11ea-8cff-7d3ddea1951c.png)

**Comment by lilyuwuu** [comment]
There is now a GUI again for F3, called F3XSwift! https://github.com/vrunkel/F3XSwift

Seems to work just fine.

**Comment by lilyuwuu** [comment]
Resolved by #1802
