### ISSUE TITLE
Broken github repository on ntrboot section

### ISSUE THREAD

**Issue by Liger0** [hacks-guide/Guide_3DS#1742]
https://3ds.hacks.guide/ntrboot.html

The "certain flash chips" link related to DSTT flashcarts is broken.

Just to take the chance since I am unsure if it's related to that guide, I was just wondering around because my dstti bricked after trying to flash a kernel with no reason (it stopped at 0.78% forcing me to restart), and I was trying to find any way to unbrick it, but without any luck, so let me know if there is anything I can do..

**Comment by aspargas2** [comment]
Thanks for reporting the broken link; I will fix that shortly. About your DSTT, where you just trying to flash the regular flashrom back to the card after using ntrboot with it, or were you trying to do something else? What were you using to flash it?

**Comment by Liger0** [comment]
For the dstti, it isn't really related to the reason it failed, I mainly asked if any of the known tool can be used to recover it, which I would appreciate.
To update it I used the official DSTTi DSi 1.4.3 / 3DS V2.1 Update Patch (TTi_1.43_1.44c_3DS2.1).
Guides about unbricking cartridges would be awesome.
Thank you.

**Comment by aspargas2** [comment]
The link on the ntrboot page is now fixed. About your specific issue, I really don't know anything about the dstti specifically myself, but I'll see if I can find someone who does.

**Comment by FrozenChen** [comment]
I dont know your specifics for your clone but its possible you can unbrick your flashcart by using the same flasher, some flashers let you hotswap the cartridge before flashing the firmware, if you have another flashcart you could launch the flasher then swap the flashcart for the bricked flashcart before flashing and hopefully unbricking it

**Comment by Liger0** [comment]
Mine wasn't a clone. Either way I'll try it, thanks.

**Comment by FrozenChen** [comment]
Fixed in commit 8146ec9

**Comment by Liger0** [comment]
> 
> 
> I dont know your specifics for your clone but its possible you can unbrick your flashcart by using the same flasher, some flashers let you hotswap the cartridge before flashing the firmware, if you have another flashcart you could launch the flasher with the working flashcart then swap the flashcart for the bricked one before flashing, and hope the firmware flash unbricks it

Either way, it doesn't work. :C
