### ISSUE TITLE
Any reason seedminer.hacks.guide subdomain is used over main BFM domain?

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [hacks-guide/Guide_3DS#1777]

**Comment by Oreo639** [comment]
Not entirely sure what the question is, but the reasoning given was that it would be easier to type. (it's just a CNAME to BFM)
It was done with permission of the operator of BFM (deadphoenix).

Sorry if I am misunderstanding your question.

**Comment by ThatNerdyPikachu** [comment]
Yup, you understood it fine. Thanks!

PS: Thanks for void-unsanitary :^)

**Comment by Oreo639** [comment]
Np.
