### ISSUE TITLE
Implement seedminer-less method for New 3ds on latest fw

### ISSUE THREAD

**Issue by safan41** [hacks-guide/Guide_3DS#1781]
In case you aren't already aware, https://github.com/zoogie/new-browserhax dropped, making cfw even easier for New 3ds to attain without the need of a movable.sed (just running slotTool from hbl and using usm).

**Comment by lilyuwuu** [comment]
We're aware. The guide requires restructuring to make new-browserhax a primary method as it would once again separate the consoles into n3ds and o3ds, and the exact order/what methods should be primary is still being discussed
