### ISSUE TITLE
3DS Hacks Guide Errors

### ISSUE THREAD

**Issue by dwain12435** [hacks-guide/Guide_3DS#1786]
With the new update, it says that Homebrew Launcher (Browserhax 2020) works on 11.13-11.13, but it actually works from 11.10.0-43# through 11.13.0-45#. Also, the instructions say to copy the slotTool.3dsx from the unSAFE_MODE archive to the 3ds folder and to copy the usm.bin to the root of the SD Card, but this is incorrect. You actually need to copy the entire slotTool folder to the SD:/3ds folder, as the slotTool.3dsx requires the included xml file to run. The slotTool.3dsx with its xml file are standalone, which means that they do not require the usm.bin from the unSAFE_MODE archive.

I know what I am talking about, I wrote [a guide on this](https://gbatemp.net/threads/easy-way-to-hack-any-3ds-this-method-is-way-easier-than-plailects-guide.572993/) before a guide was up on the 3ds.hacks.guide website. Maybe you could try doing what I did in [my guide](https://gbatemp.net/threads/easy-way-to-hack-any-3ds-this-method-is-way-easier-than-plailects-guide.572993/) and only require you to download one zip file and extract it to the root of your SD card, instead of having to download a bunch of files and manually place them in the correct locations on the SD Card.

**Comment by bleck9999** [comment]
> the slotTool.3dsx requires the included xml file to run
This is not true.

**Comment by Validusername16** [comment]
> With the new update, it says that Homebrew Launcher (Browserhax 2020) works on 11.13-11.13, but it actually works from 11.10.0-43# through 11.13.0-45#.

who cares if it works on 11.10.0-43, that's not a reasonable firmware version to end up on, and even if you did, you'd get update nagged

**Comment by ItsPizzaTime1501** [comment]
> I'm a 3DS hacker who wrote a great 3DS hacking guide that is far better than the one at 3ds.hacks.guide. My guide can be found at my URL
>
I guess ihaveamac better delete this repo, no reason for it to exist

**Comment by GlaZedBelmont** [comment]
Once you're ready to actually point out relevant errors, please open another issue.
