### ISSUE TITLE
Theme Plaza domain change

### ISSUE THREAD

**Issue by Helloman892** [hacks-guide/Guide_3DS#1839]
**Pages with issue(s)**

Any page that links to Theme Plaza via https://themeplaza.eu, including [the front page](https://3ds.hacks.guide). At current, there are 68 instances of this URL (according to GitHub's search feature), largely due to localisation of the guide.

**Description of the issue(s)**

As of recent legislation regarding `.eu` domains and the UK's exit from the European Union, Corin Simpson-Bryars (the site owner and primary administrator of Theme Plaza) has relinquished control of the domain `themeplaza.eu` to an associate in the EU.

As a direct result, the primary domain has been changed from `themeplaza.eu` to `themeplaza.art`. I have it on good authority that the `.eu` domain is not being abandoned, and will continue to redirect to the `.art` domain indefinitely, but for correctness' sake I feel the domain should be changed in each place it appears.

**Comment by lilyuwuu** [comment]
Change has been made in dd527419e1732f1b8fa80dad6ce830c9cbf65af5 for en_US. Will close once change is pushed to other languages via crowdin.
