### ISSUE TITLE
Godmode9 usage guide is outdated

### ISSUE THREAD

**Issue by yor-so** [hacks-guide/Guide_3DS#1877]
Hi. I wanted to convert a installed title, specifically a game uodate to a cia file following the guide, but the GodMode9 guide is outdated. The options are different now in the latest gm9 version, so I'm not really sure how to properly backup my cia. Can the guide be updated? Thanks.

**Comment by hansoljin** [comment]
This is being worked on in #1870.

**Comment by hansoljin** [comment]
The updated guide has been merged, and this specific topic's instructions can be found at https://3ds.hacks.guide/dumping-titles-and-game-cartridges .

**Comment by MechanicalDragon0687** [comment]
resolved in d854d76
