### ISSUE TITLE
2 black screens, not guides fault, i believe.

### ISSUE THREAD

**Issue by Lordakira** [hacks-guide/Guide_3DS#1892]
**spr-001(usa)**

**sw156504797 Old 3DS xl**

**newest firmware**

**Luma3DS Version(newest)**

Luma boot (select) works
Godmode9 (start) works

Regular boot produces double black screen with blue power led. Have left on overnight, because I read on discord that it could just be a slow boot. It has not recovered. Not sure if needed file was deleted on accident. Problem occurred when attempting to add ds games using the forwarder. A few failed so I was deleting tickets. There was quite a few so I was trying to go through quickly (around 20-30 from a set failed)  may have deleted something I wasn't supposed to or possibly launch an invalid title. But both screens turned black. So thinking I deleted a fundamental file, I removed sd cleared it off and was going to reset it with backup but cannot find backup USB. So I reloaded all files from the guide to reset all the basic files. Used guide to re-finalize but still 2 black screens. Also tried removing the battery and removing and replacing the wifi card. Any ideas? Any particular file that might cause a non-boot? 
![162570062206451715467155015020](https://user-images.githubusercontent.com/87100197/124840843-7c8ea400-df51-11eb-84bc-81066e79e7a3.jpg)
![16257006832991717715461594918739](https://user-images.githubusercontent.com/87100197/124840889-95975500-df51-11eb-8316-05b932594562.jpg)
![1625700741827286702102713947200](https://user-images.githubusercontent.com/87100197/124840945-b65faa80-df51-11eb-9d10-0c846010749c.jpg)

**Comment by lilyuwuu** [comment]
You will probably get better help with your issue from [Nintendo Homebrew](https://discord.gg/MWxPgEp) on Discord. This issues page is for problems or suggestions for 3ds.hacks.guide.

**Comment by Lordakira** [comment]
Update. Left running for an hr and now it has shown an error
![16257053058421360472492728149060](https://user-images.githubusercontent.com/87100197/124845419-53274580-df5c-11eb-96f3-8e0d5ea8e68c.jpg)

**Comment by lilyuwuu** [comment]
This issue was resolved by a [ctrtransfer](https://3ds.hacks.guide/ctrtransfer).
