### ISSUE TITLE
Find fail

### ISSUE THREAD

**Issue by Necrolinkwire** [hacks-guide/Guide_3DS#1916]
**System model**

**Firmware version**

**Luma3DS Version(If applicable)**

**Guide Section(If applicable)**

**Comment by Necrolinkwire** [comment]
![IMG_0298](https://user-images.githubusercontent.com/90569508/132995897-e3b608c7-7611-41a3-8556-67529e91d981.PNG)

**Comment by lifehackerhansol** [comment]
This image has nothing to do with any part of the guide. Please contact the script creator for help on your issue.

**Comment by lilyuwuu** [comment]
Closed, invalid
