### ISSUE TITLE
Problem to installbotstraap 

### ISSUE THREAD

**Issue by Necrolinkwire** [hacks-guide/Guide_3DS#1917]
![IMG_0298](https://user-images.githubusercontent.com/90569508/132995919-99d8cb1b-4841-438a-86ac-564c2f64978b.PNG)

**Comment by lifehackerhansol** [comment]
Duplicate of https://github.com/hacks-guide/Guide_3DS/issues/1916.

**Comment by lilyuwuu** [comment]
Closed, duplicate/invalid
