### ISSUE TITLE
Add credits for nord theme

### ISSUE THREAD

**Issue by yupyup0666** [hacks-guide/Guide_3DS#1921]
Whilst not necessary according to the license, people who made the theme are dope people and deserve some credit. Also helps people wanting to know what the theme is. 

(Off topic, I actually noticed this while in a windowed terminal on top of my browser watching Modern Vintage Gamer and the colors matched up identically. Pretty funny)

**Comment by lifehackerhansol** [comment]
Am slightly lost on this issue. What theme are we talking about exactly?

**Comment by MechanicalDragon0687** [comment]
The default minimal mistakes theme used is the "nord" theme

**Comment by MechanicalDragon0687** [comment]
Anyone know where the nord theme came from or is it a transcription of the colors from https://github.com/arcticicestudio/nord ?
