### ISSUE TITLE
Homebrew launch issue

### ISSUE THREAD

**Issue by Boffice** [hacks-guide/Guide_3DS#1991]
**System model**
Old 3DS

**Firmware version**
11.15.0-47E

**Luma3DS Version(If applicable)**
Luma3DSv10.2.1

**Guide Section(If applicable)**

[](https://3ds.hacks.guide/finalizing-setup#section-iii---homebrew-launcher)[](https://3ds.hacks.guide/finalizing-setup#section-iii---homebrew-launcher)Section III - Homebrew Launcher

-----

**11. Your device should load the Homebrew Launcher**
![IMG_20220314_144942](https://user-images.githubusercontent.com/44022848/158159048-6a976905-5294-4723-ade9-b407e6a44b05.jpg)

Get error when i launch Download Play application

**Comment by lifehackerhansol** [comment]
Please go to the [Nintendo Homebrew Discord server](https://discord.gg/MWxPgEp) for support.
