### ISSUE TITLE
FAQ page has no sidebar

### ISSUE THREAD

**Issue by lifehackerhansol** [hacks-guide/Guide_3DS#1993]
**Pages with issue(s)**

faq.txt

**Description of the issue(s)**

Has no sidebar. Kind of hard to navigate. 

I believe the issue is because it's using a custom HTML <a> to do this, instead of a standard header. I'm not too sure what the use case for that is, though...

**Comment by lilyuwuu** [comment]
Partially resolved by a8412cbc9758d9448dbd0f26cc0769d5cadd9925, but TOC does not contain links to individual FAQ items. Leaving open until we fix that or decide that that's okay
