### ISSUE TITLE
boot9strap folder missing from screenshot in Finalizing Setup

### ISSUE THREAD

**Issue by Jorpho** [hacks-guide/Guide_3DS#2004]
**Pages with issue(s)**

https://3ds.hacks.guide/finalizing-setup

**Description of the issue(s)**

The screenshot in Finalizing Setup lacks a boot9strap folder.  While the page does say that "you may have extra files or folders on your SD card", the bottom of the page explicitly refers to a "boot9strap folder on your SD card".

**Comment by lilyuwuu** [comment]
The boot9strap folder will be created in the START+SELECT+X action if it does not already exist. It is technically separate from the boot9strap folder that is necessary when installing boot9strap via PicHaxx, Soundhax, or ntrboot. 

I do recognize that this should probably be made less ambiguous, though. Adding the folder to the screenshot creates the reverse issue of other people following the guide (that is, people following unSAFE_MODE or Fredtool) _not_ having the boot9strap folder. Those methods aren't currently the main recommended one, but remain a valid use case for KOR and TWN consoles and will become the dominant Seedminer-based method after eShop closure should no alternative be found.

**Comment by Jorpho** [comment]
Excellent points. Perhaps it would be worth considering the addition of "The boot9strap folder will be created if it does not already exist" to the end?

**Comment by lilyuwuu** [comment]
Yeah, will probably add that line. It's not super important anyhow - dumping bootrom/OTP isn't something that most people need to manually do.

@lifehackerhansol actually maintains a separate page for alternate methods, seen [here](https://3ds-legacy.hansol.ca/get-started). Freakyhax is on that list.

Oot3dhax is a bit more iffy. I'm pretty sure it'd work fine on latest FW with some tinkering, but no one has bothered to build the necessary save files for it. The bigger sticking point is that the method requires either a powersaves or a physical cartridge + modded 3DS, making it less accessible than kartdlphax. It might be worth adding to the legacy page, but probably not to the main guide.
