### ISSUE TITLE
Uninstall CFW: Brick warning is not applied to (full) Section V

### ISSUE THREAD

**Issue by kevincrans** [hacks-guide/Guide_3DS#2047]
**Pages with issue(s)**
Uninstall CFW

https://3ds.hacks.guide/uninstall-cfw
**Description of the issue(s)**
"If you skip this section, you may BRICK your device!" is applied to section III, but not to section V.

I'm a fool for bricking my device, with this as excuse, but why not save some fools 3ds' while u now know how?

**Comment by lilyuwuu** [comment]
Keep in mind that the safety test (booting stock) is performed _while you still have illegitimate apps installed_. The presence of illegitimate apps alone should therefore not automatically result in a brick. You said something about "survived for a week" in the assistance channels - what exactly happened?

**Comment by kevincrans** [comment]
I played RPG Maker FES and it crashed a few times (like always).
It also froze a lot (at least with CFW installed) then I always successfully restart, but this time (CFW uninstalled), I restarted, but the screen wouldn't go on, only a blue light.

**Comment by lilyuwuu** [comment]
Closing due to lack of evidence/unclear what's actually going on (most likely coincidental hardware issue due to aforementioned safety test logic)
