### ISSUE TITLE
no 11.16 firms on hardmod page

### ISSUE THREAD

**Issue by foxsouns** [hacks-guide/Guide_3DS#2108]
**Pages with issue(s)**
https://3ds.hacks.guide/installing-boot9strap-(hardmod)

**Description of the issue(s)**
Page needs to be updated to display a new firm or update text. (Need find out if 11.16 uses a new kernel version (not likely) and update accordingly.)

**Comment by lifehackerhansol** [comment]
I believe there is a new nfirm. We haven't made a new torrent for it yet.

Perhaps I'll throw a warning on the page for now until I get my hands on it.

**Comment by foxsouns** [comment]
@lifehackerhansol Oh, I think could make the warning! I'll make the PR.
