### ISSUE TITLE
the ssloth proxy is dead

### ISSUE THREAD

**Issue by justwantedtoupdatebrowserhaxtutorial** [hacks-guide/Guide_3DS#2133]
https://3ds.hacks.guide/installing-boot9strap-(ssloth-browser)

The proxy wasn't working for me (gave me error  032-1221) so i used dns90 instead and it worked, so i request a change of the ssloth section so nobody will face the issue I got.

**Comment by lifehackerhansol** [comment]
1. 90dns has nothing to do with the 3DS.
2. The proxy is working. We had someone successfully hack their device a few hours ago.
3. I don't recall another person hosting a proxy or DNS server that actually hosts the forged SSL certificates.

Thus the page will not be changed.
