### ISSUE TITLE
Fredtool verification steps expect a first boot and save of luma

### ISSUE THREAD

**Issue by MechanicalDragon0687** [hacks-guide/Guide_3DS#2138]
**Pages with issue(s)**

https://3ds.hacks.guide/installing-boot9strap-(fredtool)

**Description of the issue(s)**

section 5 step 13 powers off the device without a luma config save
section 6 expects a luma config save to have happened

**Comment by lifehackerhansol** [comment]
why is that different anyway
couldn't we just do the same verification as any other page, but instead add zoogie's troubleshooting instead of the regular Luma troubleshooting steps
