### ISSUE TITLE
Guide to upgrade to larger SD Card does not work

### ISSUE THREAD

**Issue by nakoeppen** [hacks-guide/Guide_3DS#2157]
**Pages with issue(s)**
Any pages explaining how to upgrade SD Card

https://3ds.hacks.guide/faq#q-how-do-i-upgrade-my-sd-card

**Description of the issue(s)**
The current guide to upgrade to a larger SD card does not work as intended, in my experience. Due to 3DS encryption of SD Cards, the process to upgrade to a larger SD card is a bit more nuanced than anticipated. As it stands, the current guide will not retain themes nor games/apps on the home screen after the transfer. A Reddit comment gave me a functioning solution. I copied and made the steps more streamlined below:
1. Format the new card to FAT32. For 128GB cards, an allocation size of 65536 is recommended. SD cards larger than 128GB are not recommended due to known issues with GBA graphics and custom themes. (<- taken from existing page)
2. Backup all contents of old card to PC. 
3. Insert new card to 3DS, turn 3DS on, let it create the Home settings on new SD card
4. Remove the new card from the 3DS and insert it to PC
5. Copy everything from the old card to the new one
6. Go inside the Nintendo 3DS folder
7. Open folder with 32 character name (we will call id0). Inside id0 is another folder with a 32 character name (we will call id1).
8. Copy the contents of the 'old' id1 folder (the one you backed up) into the 'new' id1 one, replace/overwrite file in destination/merge if necessary
9. Insert new card in your 3DS and enjoy!

**Comment by lilyuwuu** [comment]
This shouldn't be necessary. The 3ds should not need to create home menu settings on the new card before it can be used - it'll use the old sd's id1 just fine if you format the card and copy paste before using the new card in the 3ds. Anew one is only created if no data is present on the card, to prevent accidentally merging the contents of two sd cards (which would be bad).

What I'm guessing happened here is that you put the sd card into the 3ds after formatting but before copying over the old sd data, which would make the 3ds use and prioritize the newly created id1. What you're supposed to do is format the card, copy the data, then put the sd into the 3ds which shouldn't create a new id1 (this could admittedly be clarified, but as it stands stuff about sd cards is a bit disorganized and probably needs reorganization anyhow).

**Comment by lilyuwuu** [comment]
Closing due to no response
