### ISSUE TITLE
hShop (READ the new part below, even though I made a closed and locked PR)

### ISSUE THREAD

**Issue by Minionguyjpro** [hacks-guide/Guide_3DS#2168]
It is NOT only pirated stuff. It includes Homebrew, which is not actually seen as piracy. I read that at some sites.
I can update the page to say that it is for Homebrew and other stuff, and give them a notice and/or warning that says it also includes free stuff, but this is officialy not allowed.

Reference:
https://www.answerparadise.net/is/is-it-safe-to-update-3ds-with-homebrew/#:~:text=Is%20homebrew%20legal%20for%203DS%3F

https://www.quora.com/Is-it-legal-to-hack-homebrew-a-Nintendo-3DS#:~:text=Yeah%2C%20it%20is%20completely%20legal.%20Hacking%20only%20becomes%20illegal%20when%20you%20enter%20someone%27s%20device%20without%20their%20permission%2C%20or%20if%20you%20were%20to%20hack%20into%20a%20device%20to%20gather%20illegal%20items%20and/or%20use%20it%20for%20illegal%20purposes.

**Comment by ihaveamac** [comment]
No, the fact that it actively enables piracy is what makes it not allowed. The fact that it also links to homebrew doesn't change that fact. (Also, we already have Universal-Updater for homebrew.)

**Comment by Minionguyjpro** [comment]
Is it also disallowed to make guides about certain Homebrew?

**Comment by ihaveamac** [comment]
You can put most stuff at https://wiki.hacls.guide (but still nothing about piracy tools or websites are allowed)

**Comment by Minionguyjpro** [comment]
Ok, so I should be able to make a guide for example some sort of homebrew like ThirdTube (New YouTube client for 3Ds, as the other one shut down.)?

**Comment by Minionguyjpro** [comment]
> You can put most stuff at https://wiki.hacls.guide (but still nothing about piracy tools or websites are allowed)

So, I must use this site instead of 3DS hacks?

**Comment by ihaveamac** [comment]
3ds.hacks.guide primarily focuses on homebrew and custom firmware setup. The wiki is basically everything else after that. https://wiki.hacks.guide/wiki/Hacks_Guide_Wiki:About

You could make a page about ThirdTube if you want. Maybe at https://wiki.hacks.guide/wiki/3DS:ThirdTube ?

**Comment by Minionguyjpro** [comment]
> 3ds.hacks.guide primarily focuses on homebrew and custom firmware setup. The wiki is basically everything else after that. https://wiki.hacks.guide/wiki/Hacks_Guide_Wiki:About
> 
> You could make a page about ThirdTube if you want. Maybe at https://wiki.hacks.guide/wiki/3DS:ThirdTube ?

Good one. I also know GameBrew. I understand what you mean. But, one more thing, I don't know of you know of the wii.guide site, but it looks like there is also homebrew? Or is that also part of the installation, for example that you use USB Loader GX to play USB games?

**Comment by Minionguyjpro** [comment]
> wii.guide is unaffiliated

Ok. Have a nice day!
