### ISSUE TITLE
How can I start this guide's development environment ?

### ISSUE THREAD

**Issue by sweshelo** [hacks-guide/Guide_3DS#2169]
**Description of the issue(s)**

I'm translating this guide into Japanese, but i don't understand how to start development environment. Could you tell me how to start that and what i need ?

**Comment by MechanicalDragon0687** [comment]
checkout the translation project at https://crowdin.com/project/3ds-guide

**Comment by sweshelo** [comment]
Thank you for your help. Ill check it.
