### ISSUE TITLE
IR sensor does not respond with Walk with me

### ISSUE THREAD

**Issue by jumanjids** [hacks-guide/Guide_3DS#2170]
**System model**

Old 3DS, 2DS XL

**Firmware version**

11.16.0-49E

**Luma3DS Version(If applicable)**

v11

Hi,
IR is not working with Walk with me. Tested with two old 3DS's and 2DS XL. Got two 2ds that are not hacked and it is working fine. Any ideas how to sort it out. 
Thanks

**Comment by MechanicalDragon0687** [comment]
This issue tracker is to track issues with the guide not for troubleshooting individual 3ds issues. please visit the discord at https://discord.gg/MWxPgEp for assistance in the appropriate channel
