### ISSUE TITLE
[Some type of request] Making an all-in-one CIA installer for GM9 and include in guide?

### ISSUE THREAD

**Issue by Minionguyjpro** [hacks-guide/Guide_3DS#2185]
Hello there, I am planning to make an all-in-one installer which installs all the default needed apps (FBI, Homebrew Launcher, etc.) using a GodMode9 script, which can be ran from GodMode9, and automatically installs all the apps, which first need to be downloaded to the SD card. Can this be added to the guide if I get it to work?

**Comment by MechanicalDragon0687** [comment]
One of the issues with this is that if someone has not yet installed any apps, then godmode9 is unable to install apps. GM9 does not create the database files on the sd card, FBI does.

**Comment by Minionguyjpro** [comment]
> 

That's true, yes, but I thought it may have been handy to automatically install these, without needing to do all the FBI things. Also so you didn't need to manually launch Homebrew launcher and so. Are these database files different for everyone?

**Comment by MechanicalDragon0687** [comment]
they are encrypted to the system, but gm9 gives you unencrypted access. it is possible to create and import a title.db if one doesnt exist, but i would expect excessive testing of this to ensure you dont accidentally wipe out someone's installed games

**Comment by Minionguyjpro** [comment]
Okay...

**Comment by Minionguyjpro** [comment]
Not planning to make it due to some issues.
