### ISSUE TITLE
How can I even view the website while at school?

### ISSUE THREAD

**Issue by rdistiso** [hacks-guide/Guide_3DS#2191]
I can't take my friend's 2ds home or else I get in trouble w/ my dad. Can you make another page that won't be blocked by FortiGuard or Cisco Umbrella
![image](https://user-images.githubusercontent.com/116186005/219037789-fdea3848-b4fe-4cfb-8b35-b855a5dcf936.png)

**Comment by Gruetzig** [comment]
you can create a fork and use github-pages to view it

**Comment by rdistiso** [comment]
But I have little experience in coding

**Comment by rdistiso** [comment]
Another question, how do I do that?

**Comment by rdistiso** [comment]
Thanks
