### ISSUE TITLE
Unable to complete "Section IV - Overwriting DS Connection Settings"

### ISSUE THREAD

**Issue by NSilky** [hacks-guide/Guide_3DS#2213]
When i try to copy "Haxxxxxxxx! (Dsinternet) to system memory it says "Data could not be copied." I checked everything twice but cannot get past this step. I have 1,054 open blocks on my 3ds XL (old version, current update). Any help at all would be greatly appreciated.

**Comment by MechanicalDragon0687** [comment]
This issue tracker is for issues with the guide itself not troubleshooting. please visit the discord for assistance
