### ISSUE TITLE
Blackouts

### ISSUE THREAD

**Issue by snan** [hacks-guide/Guide_3DS#2220]
**System model**

2DS (original "wedge shape")

**Firmware version**

Sys 11.16.0-49E

**Luma3DS Version(If applicable)**

Luma3DS v11.0

**The Issue**

The system "blacks out"—both screens go black, sound shuts off, and a few minutes later (sometimes seconds, other times several minutes) it's back on right where it left off. It's in any game, including the Sound Player and the system settings. I've been on Luma for a while but this happened immediately after updating to Luma 11 & sys 11.16.

**Comment by MechanicalDragon0687** [comment]
This issue tracker is for issues with the guide itself not troubleshooting your console. please visit the discord for assistance

**Comment by snan** [comment]
There literally is a "press here if there is some issue with the console after completing the guide" button in this issue tracker 💁🏻‍♀️

What Discord is that?

**Comment by Gruetzig** [comment]
Randal seems to be a bit lost, but  they mean and I also suggest the Nintendo Homebrew Discord for faster answers. 
https://discord.gg/nintendohomebrew
