### ISSUE TITLE
Section III - Select a Method" not redirecting after entering the system version

### ISSUE THREAD

**Issue by rune9rod** [hacks-guide/Guide_3DS#2225]
**Pages with issue(s)**

https://3ds.hacks.guide/es_ES/get-started

**Description of the issue(s)**

It's a problem that only happens with the guide's other languages (it's fine if you are browsing the English version). Basically, if you are in the Spanish version, for example, and try to enter your console's version in "Section III - Select a Method" of the "Get Started" page, nothing happens after pressing "Confirm"; the button just doesn't respond. Of course, you can easily solve it by switching to English, but I thought it was an issue worth mentioning.

**Comment by Gruetzig** [comment]
What did you enter for the version?

**Comment by rune9rod** [comment]
Oops, I forgot to add a description. It's a problem that only happens with the guide's other languages (it's fine if you are browsing the English version). Basically, if you are in the Spanish version, for example, and try to enter your console's version in "Section III - Select a Method" of the "Get Started" page, nothing happens after pressing "Confirm"; the button just doesn't respond. Of course, you can easily solve it by switching to English, but I thought it was an issue worth mentioning.

**Comment by lifehackerhansol** [comment]
Should be fixed now, but I'm going to leave this issue up so I can fix the issue of EN guide and all other translations constantly desyncing.
