### ISSUE TITLE
CTRTransfer Ticket Copy script did not copy tickets; suggest alternative?

### ISSUE THREAD

**Issue by RokonShimo** [hacks-guide/Guide_3DS#2236]
**Pages with issue(s)**

CTRTransfer
https://3ds.hacks.guide/ctrtransfer

**Description of the issue(s)**

The CTRTransfer Ticket Copy tool failed to export tickets for all installed software (not returning an error message) and those that it did export did not allow access to any installed titles. Using faketik correctly generated tickets for all titles. Would it be helpful to add faketik to that page as a backup plan? https://github.com/ihaveamac/faketik/releases

**Comment by lifehackerhansol** [comment]
faketik was added to the guide in commit 774bb870b14ecd8cbb908d4931eb660778f70566.
