### ISSUE TITLE
Deleted all my Cias

### ISSUE THREAD

**Issue by MasterX125** [hacks-guide/Guide_3DS#2253]
I was just going to finalize the steps to hack my 3ds, I was using the hack guide and in Finalizing Setup, Section VII- Cleanup SD card it states that it “removes unnecessary files” so I did it and it deleted my 15 cias of games I had there, I’m really sad as it took time a lot of time to download them and redownloading them again is going to be a hassle ;-;, can there please be a warning message that all cias will be deleted in that step to prevent happening on someone else.
![505F941F-05D3-41BD-8547-470DC2C2F228](https://user-images.githubusercontent.com/131830343/234435685-04c0a488-48f1-4e09-82b5-18d1ca468ad1.jpeg)

**Comment by MechanicalDragon0687** [comment]
luckily in a previous section (section 5 i believe) you already "install and delete all cias" so this is a non-issue if you are following the guide since those cia files are already gone
