### ISSUE TITLE
clearity on a small step

### ISSUE THREAD

**Issue by StrategyMamber** [hacks-guide/Guide_3DS#2255]
**Pages with issue(s)**

installation section 5 in step 9,
and in finalizing setup section 3 step 9

https://3ds.hacks.guide/installing-boot9strap-(hbl-usm)
https://3ds.hacks.guide/finalizing-setup

**Description of the issue(s)**

I feel the step press home in download play and then close it would be more clear as two steps.

for example by making 9, press home, and then 10 press close on the bottom screen to close the application.
it's a small difference. yet I would argue it does make it easier to know what you do. especially if you do have not much experience with a 3ds or how to properly close an app. seeing as a kid I usually just opened another app to continue playing.

just thought this might make things easier on others.

**Comment by MechanicalDragon0687** [comment]
I would agree with that. This sounds reasonable and does tend to confuse some folks that dont realize that pressing home does not actually "close" the application.

https://github.com/hacks-guide/Guide_3DS/blob/master/_pages/en_US/include/launch-hbl-dlp.txt#L9

line linked above for reference
