### ISSUE TITLE
Modded 3ds with no fbi

### ISSUE THREAD

**Issue by AdhmAlateiat** [hacks-guide/Guide_3DS#2275]
I got a modded 3ds from a while back and the sd card that had all of the files broke, so now my 3ds has Luma3ds V12.0.1 but doesn't have homebrew or FBI and I don't know what to do here, anyone knows how to fix this?

**Comment by lilyuwuu** [comment]
Follow [this page](https://3ds.hacks.guide/restoring-updating-cfw). Continue to the "If you wish to re-install or update other homebrew applications, continue to [Finalizing Setup](https://3ds.hacks.guide/finalizing-setup)" section to... well, reinstall homebrew applications.

This repository isn't really for tech support issues. If you need further assistance, you'd be better served on [Discord](https://discord.gg/MWxPgEp).
