### ISSUE TITLE
Japanease ssloth and bootstrap not possible

### ISSUE THREAD

**Issue by Myrtylle** [hacks-guide/Guide_3DS#2307]
**Pages with issue(s)**
Across multiple pages
False direction given

None

**Description of the issue(s)**
Since the eshop closed this is not possible anymore to pay to unlock the internet browser filter on 3ds consoles.

Japanease consoles have a very restrictive filter and do not allow to connect via ssloth method.

The guide keeps saying i can mod with 11.10.0-43J but it is not true since the browser filter refuse to go to the web page.

Would love to see the guide directing to another option.

**Comment by lifehackerhansol** [comment]
Something isn't right. Just last week someone on a Japanese model was able to hack their console using SSLoth-Browser. What's happening suddenly? What step is breaking?

**Comment by TheMasterOfMike** [comment]
> Something isn't right. Just last week someone on a Japanese model was able to hack their console using SSLoth-Browser. What's happening suddenly? What step is breaking?

The filter is only a thing with New 3ds Japanese consoles - after the removal of credit card support on the Japanese eShop in January 2022, it could no longer be removed.

**Comment by lifehackerhansol** [comment]
> > Something isn't right. Just last week someone on a Japanese model was able to hack their console using SSLoth-Browser. What's happening suddenly? What step is breaking?
> 
> The filter is only a thing with New 3ds Japanese consoles - after the removal of credit card support on the Japanese eShop in January 2022, it could no longer be removed. (Though if it was already removed, you're fine)
> 
> (Relevant Nintendo page: https://www.nintendo.co.jp/support/information/2021/0720.html)
> 
> These devices are in a hard spot in general, thinking about it, since I'm not sure if they would be able to do super-skaterhax either should they update to 11.17

That is not what I asked. I'm fully aware that the filter exists. What I don't understand is that people were able to follow this on Japanese N3DS ages ago when it was the main path. Was GitHub always on the blocklist or something?

**Comment by lilyuwuu** [comment]
Update: Just tested on my own JP N3DS unit on 11.13.0-45J. I cannot reproduce the issue you're experiencing (the website is able to be accessed).

Are you sure your proxy settings are correctly set?

**Comment by Myrtylle** [comment]
> 

My bad, I was not reading yhe error message correctly. It end up working just fine. Thank you all for quickly replying. It was just me being dumb for a moment! Haha
