### ISSUE TITLE
gm9 backup path incorrect in finalization step

### ISSUE THREAD

**Issue by cmcginty** [hacks-guide/Guide_3DS#2309]
**Pages with issue(s)**

https://3ds.hacks.guide/finalizing-setup

**Description of the issue(s)**

<img width="693" alt="image" src="https://github.com/hacks-guide/Guide_3DS/assets/277249/e4cecce6-bae2-441b-96e2-1ec6b21a5d85">

Step 11 indicate "/gm9/backups" is the source path. This does not exist, and should probably be "/gm9/out" instead.

**Comment by lilyuwuu** [comment]
The script uses /gm9/backups/ as outpath
