### ISSUE TITLE
issues with the tutorial

### ISSUE THREAD

**Issue by lemmings32** [hacks-guide/Guide_3DS#2316]
**Pages with issue(s)**

https://3ds.hacks.guide/installing-boot9strap-(menuhax)

**Description of the issue(s)**
step 7 on the page 
Copy bb3.bin from the Release .zip to the root of your SD card, replacing the current file

does not state to run the executable and copy the movable.sed to the directory before copying the bb3.bin to get edited bb3.bin file

**Comment by lilyuwuu** [comment]
Bb3.bin is not console-specific
