### ISSUE TITLE
New or updated images for nimdsphax

### ISSUE THREAD

**Issue by lifehackerhansol** [hacks-guide/Guide_3DS#2329]
**Pages with issue(s)**

Needs updates:
- images/screenshots/bb3/bb3-root-layout.png
- images/screenshots/pichaxx-root-layout.png
- ~~images/screenshots/skater-root-layout.png~~ 6b76efc915555d3cf46dcd7159ba59094bc6b31e

Needs new images:
- freakyhax
- kartdlphax
- kartminer7
- menuhax
- ninjhax2-dx
- smilehax-iie
- steelhax

**Description of the issue(s)**

Needs nimdsphax images

**Comment by lilyuwuu** [comment]
delegating kartminer7 and kartdlphax to #2321
