### ISSUE TITLE
Add troubleshooting option for SSLoth-Browser

### ISSUE THREAD

**Issue by t895** [hacks-guide/Guide_3DS#2334]
**Pages with issue(s)**
https://3ds.hacks.guide/troubleshooting#installing-boot9strap-ssloth-browser

**Description of the issue(s)**
I'm not sure what causes this but there can be a case where if you try to run browser hax, you get kicked to the home menu with the error "An error has occurred. Please save your data in any software currently in use, and then restart the system."

There's a thread about it [here](https://gbatemp.net/threads/boot9strap-wont-launch-through-qrcode-github-link.632864/post-10159382) and the solution is to initialize browser save data. I'm not familiar with how the site works so I couldn't make a PR but hopefully this is enough information to add the troubleshooting step to help anyone else with the issue. I did notice that under "Opening the browserhax QR code or URL crashes", it has the same solution but I didn't think to try that in the moment (I could just be dull here).

**Comment by lilyuwuu** [comment]
I think this might be the same issue as "An error has occurred, forcing the software to close..." (white message box)"? But if resetting browser save data is indeed a possible solution for that error then yeah it should be amended me accordingly.

**Comment by t895** [comment]
I tried the option under that step as well and nothing changed. Resetting browser data got me into the installer.

**Comment by lilyuwuu** [comment]
yeah i'm just saying that it sound like the error that you are getting IS that white message box. Our troubleshooting is probably still wrong in that case though.

**Comment by t895** [comment]
Ah sorry. Maybe you could list both options under that header anyways?

**Comment by lilyuwuu** [comment]
most likely will do that, yeah. Kind of weird to have 'browser crashes' as a separate troubleshooting step anyway when two things that are described (error as black screen with text and error with white message box) ARE a form of crash
