### ISSUE TITLE
SD formatting guide: SD Association's SD Card Formatter is now available for Linux

### ISSUE THREAD

**Issue by mariomadproductions** [hacks-guide/Guide_3DS#2368]
SD Association released a Linux version: https://www.sdcard.org/downloads/sd-memory-card-formatter-for-linux/
So this should probably be integrated into the Linux section of SD formatting guide, like it is for Windows/Mac (maybe leaving the built-in Linux tools as a alternative option).

**Comment by mariomadproductions** [comment]
@Gruetzig no need to be shy

**Comment by Gruetzig** [comment]
It doesnt look like its open-source

**Comment by mariomadproductions** [comment]
Yeah this isn't an open source tool. This is a Linux version of the tool recommended on the Windows and Mac pages. I agree it would be a good idea to maintain the instructions for the open source tools (in addition).

**Comment by Gruetzig** [comment]
Whats the advantage of using that? I downloaded it and it seems to be a cli tool. mkfs.fat is preinstalled on most if not all distros, and it seems like unnecessary extra downloading.

**Comment by mariomadproductions** [comment]
I'm not sure what the advantage is exactly, but the guide suggests there is some advantage over third party/OS tools.

**Comment by danny8376** [comment]
it's only used for windows afaik?
we use it on windows as the built-in one is not usable at all
it's not the case for mac, and surely linux
