### ISSUE TITLE
Switch Seedminer Mii from Manual Mining to MovableQ

### ISSUE THREAD

**Issue by TophattedWasTaken** [hacks-guide/Guide_3DS#2381]
Manual mining is dead. Every time somebody asks to be mined in the assistance channels, we just send them to MovableQ. I think that we should skip the assistance channel redirection and make our Seedminer Mii guide use MovableQ, like how Seedminer uses Bruteforce Movable. 

(Current version [here](https://github.com/TophattedWasTaken/Guide_3DS/blob/master/_pages/en_US/seedminer-(mii).txt), incredibly unfinished. Help appreciated. I'll run the site locally every so often to make sure nothing broke)

**Comment by lilyuwuu** [comment]
This is TBD, we're waiting on @cm-360 for what to do with MovableQ. The plan is definitely to use it for Mii mining at some point though (and maybe for normal mining too, for the last few months of that being a possibility)

**Comment by cm-360** [comment]
I've just been waiting on adding @danny8376's distributed Mii mining functionality to my instance and then I'd say its about ready to go. I'm in my semester's midterm week(s) right now so it has been a bit crazy

**Comment by TophattedWasTaken** [comment]
Awesome. Should I keep maintaining this or not?

**Comment by lilyuwuu** [comment]
Go for it (we'll need to make the switch at some point anyway), and will also keep this issue open until that's done

**Comment by TophattedWasTaken** [comment]
Alright.

**Comment by lifehackerhansol** [comment]
Given you've already started work on it you may as well get a full draft done until cm360 announces the epic news. I personally gave 0 thought on actually working on the page other than "we'll need it at some point"

maybe you can throw it on a github gist and I can make that a tag while it's still in beta

**Comment by TophattedWasTaken** [comment]
[Here it is](https://gist.github.com/TophattedWasTaken/3e4d662f28d406a5067022a3fcc84df2) (Granted, I just copy pasted the text from my fork, so everything is broken.)

**Comment by TophattedWasTaken** [comment]
Going to close this unless anybody objects, since it looks like we will end up using MSET9 over Mii Mining

**Comment by TophattedWasTaken** [comment]
Closing.
