### ISSUE TITLE
Incorrect text at top of ntrboot instructions

### ISSUE THREAD

**Issue by Anonymous941** [hacks-guide/Guide_3DS#2389]
**Pages with issue(s)**

https://3ds.hacks.guide/installing-boot9strap-(ntrboot)

**Description of the issue(s)**

There's a mistake at the top of the page:

> ### Required Reading
> To use the [magnet](https://wikipedia.org/wiki/Magnet_URI_scheme) links on this page, you will need a torrent client like [qBittorrent](https://www.qbittorrent.org/download.php) or [Deluge](http://dev.deluge-torrent.org/wiki/Download).

ntrboot refers to physical magnets, not magnet links, which can't be downloaded with a torrent client [citation needed]

**Comment by Gruetzig** [comment]
At the bottom of the page, there are magnet links for the flashroms. Thats why this notice is there

**Comment by Anonymous941** [comment]
Oh, I see
