### ISSUE TITLE
[Enhancement] FBI update

### ISSUE THREAD

**Issue by paulober** [hacks-guide/Guide_3DS#2412]
**Description of the issue(s)**

FBI was archived beginning this year and hasn't been updated since end of 2022.
In order for it to perform the best it can I created a fork I plan on maintaining by compiling it with the newest homebrew 3ds sdks and maybe add some UI improvements. 

So I wanted to ask if you could think of incorporating the new FBI fork into your finalizing script?
You can find my updated fork here: [paulober/FBI](https://github.com/paulober/FBI)

**Comment by lilyuwuu** [comment]
IIRC FBI is archived because it is effectively feature-complete. If FBI were to stop working due to a 3DS update, or if your fork adds things to warrant its use over upstream FBI, then we might consider switching to your (or anyone else's) fork, but as-is there is probably little reason to do so.

**Comment by paulober** [comment]
ok
