### ISSUE TITLE
FBI Repo leads to a 404

### ISSUE THREAD

**Issue by RoblKyogre** [hacks-guide/Guide_3DS#2434]
**Pages with issue(s)**

[Finalizing Setup](https://3ds.hacks.guide/finalizing-setup)
[Region Changing](https://3ds.hacks.guide/region-changing)
[CTRTransfer](https://3ds.hacks.guide/ctrtransfer)

**Description of the issue(s)**

Seems like the owner of the FBI repo took down their GitHub account, so the link to [FBI](https://github.com/Steveice10/FBI/) now leads to a 404.
Unsure if this impacts actual setup of CFW, but may be good to switch to a fork anyways.

**Comment by lifehackerhansol** [comment]
https://github.com/hacks-guide/Guide_3DS/commit/1c3e57858e1ef79ab37f81a28afd2d91345008ef
