### ISSUE TITLE
Minor text change on https://3ds.hacks.guide/region-changing (lvl2)

### ISSUE THREAD

**Issue by chends888** [hacks-guide/Guide_3DS#2458]
**Pages with issue(s)**

https://3ds.hacks.guide/region-changing

I just noticed a minor text that might've been a typo. In "Section VI - Fixing locale-related issues" on step 14 it says: "Press (A) to unlock SysNAND (lvl2) writing, then input the key combo given", I think "lvl2" is supposed to be "lvl1", right?

Sorry if I'm wrong, I'm new to 3DS hacking and I don't even know if lvl2 writing exists.

**Comment by TophattedWasTaken** [comment]
SysNAND (lvl2) permissions are a real thing, but it does look like in this case it asks for lvl1 permissions. I'll make a pull request for this and the CTRTransfer page

**Comment by TophattedWasTaken** [comment]
Could somebody please close this issue now that it has been resolved?

**Comment by chends888** [comment]
Looks fixed to me. Awesome!
