### ISSUE TITLE
Add "disable pretendo" to unable to update troubleshooting 

### ISSUE THREAD

**Issue by stop-posting-not-good-stuff** [hacks-guide/Guide_3DS#2460]
**Pages with issue(s)**
Troubleshooting, in the "Unable to update" section

https://3ds.hacks.guide/troubleshooting
**Description of the issue(s)**
Disabling Pretendos patches fixed my issue of not being able to update. It seems like turning off third-party servers and switching back to Nintendo's official servers can fix "unable to update". However, it's not listed that turning off services such as Pretendo network can fix this issue. I ended up doing a CTRTransfer for no reason because of this. It wasn't until I talked in the homebrew discord server was I able to find out this was the problem.

**Comment by TophattedWasTaken** [comment]
I assume it isn't listed there because it's under finalizing. In theory, you wouldn't have Pretendo before doing that.
It could make sense to add an unable to update section under Issues after Installation, but that might lead to confusion. Not sure if something like this is on the wiki already.

**Comment by stop-posting-not-good-stuff** [comment]
This issue happened when I was doing TWLFix. Maybe update TWLFix guide to include disable Pretendo if updates fail.

**Comment by irowiki** [comment]
https://github.com/hacks-guide/Guide_3DS/pull/2480

PR submitted as I think this is a good idea.

**Comment by TophattedWasTaken** [comment]
Would to usecase be directing people to finalize on NH after modding, where they may have Pretendo but not all essential homebrew apps?

**Comment by irowiki** [comment]
> Would to usecase be directing people to finalize on NH after modding, where they may have Pretendo but not all essential homebrew apps?

The use case is anyone finalizing after modding or finding the troubleshooting (via google or otherwise)

https://wiki.hacks.guide/wiki/3DS:Troubleshooting#Unable_to_update_console

You'll notice this was already edited previously

**Comment by lifehackerhansol** [comment]
Fixed https://github.com/hacks-guide/Guide_3DS/pull/2480
