### ISSUE TITLE
luma3DS and godmode9 bot problem

### ISSUE THREAD

**Issue by MED1com** [hacks-guide/Guide_3DS#2506]
So, I have a 3ds Japanese region consol. I tried to mod it is downloading luma3ds and godmode9 but when I open luma3ds it would freeze up and I need to power it off. when I boot up godmode9 and press a button it would reload godmode9, it's like boot looping. pls help.

**Comment by Naim2000** [comment]
You just described a stuck or otherwise malfunctioning START button.
https://wiki.hacks.guide/wiki/3DS:Bmbt3ds
