### ISSUE TITLE
Region sawp breaking DS games

### ISSUE THREAD

**Issue by TecoTurtle** [hacks-guide/Guide_3DS#2518]
**region changeing**

**Comment by ManiacOfGitHub** [comment]
this is mentioned on the troubleshooting page

**Comment by TecoTurtle** [comment]
Oh it's I never checked

**Comment by ManiacOfGitHub** [comment]
yep right here:
https://3ds.hacks.guide/troubleshooting-post-install.html#software-issues-on-consoles-with-custom-firmware

anyways, can this issue be closed?

**Comment by TecoTurtle** [comment]
Idk how to close it I'm new to github

**Comment by TecoTurtle** [comment]
Oh nevermind
