### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Luxii-Fuxi** [hacks-guide/Guide_3DS#2520]
**Pages with issue(s)**
0

Dont have any
**Description of the issue(s)**
I ve been trying to run tomodachi life from cartridge on my 3ds
but i always get an error message:
(see attachment)
![error](https://github.com/user-attachments/assets/968431ca-3b0e-4d47-81a0-a3aefc712627)

**Comment by lilyuwuu** [comment]
Hello, this repository is for issues with the guide [3ds.hacks.guide](https://3ds.hacks.guide). Your issue appears to be unrelated to the guide itself. You may find better help with your issue over at [Nintendo Homebrew on Discord](https://discord.gg/MWxPgEp).
