### ISSUE TITLE
Eshop error 005-5602 on region changed 2DS

### ISSUE THREAD

**Issue by Duonglevu** [hacks-guide/Guide_3DS#893]
Hi, I have a Japanese 2DS, I followed Plailect's guide exactly to install A9LH and change region to US. 
After all done, I create a new NID on new region, and then I access eshop, I get the error 005-5602.
Please tell me how to fix this? Thank you very much!

**Comment by jaxrogers2** [comment]
Quote from the guide:

"Note that occasionally the eShop will inexplicably still not work for devices that it should work for. This is entirely to do with Nintendo’s servers, and I really do not have any control over it."

**Comment by Duonglevu** [comment]
The problem is that, I have over 10 devices (old 3DS, old 3DS XL, 2DS), and none of them are able to access eshop after region change, all have the save error 005-5602. So I want to ask if anyone really able to access eshop after region change or just theory? And if yes, did they follow Plailect's guide like me or some other guide? Thanks.

**Comment by jaxrogers2** [comment]
Based on the error code, this sounds like the error is caused by forgetting to set your country/region in settings to a country in the region you switched to. So if you switched from JPN -> EUR, you need to go into settings and set your country and region to somewhere in Europe.

**Comment by Duonglevu** [comment]
I'm changing my 2DS from JP to US. I've changed the region in profile setting to US, accept all agreements, and then update to latest FW (11.2). After all that, I still get the same error code 005-5602. If you have any suggestion please tell me and I'll try that. Thank you very much!

**Comment by helmergoza** [comment]
estimated friend 

i have the same problem with 50 3ds japan to usa, did you get some solution to go to eshop after the change.

**Comment by Parham75** [comment]
Hi I have the same problem error code 005-5602 after region change from JP to EU on new 3DS LL. Appreciate it if you let me know if there is a solution to this. Thank you

**Comment by aspargas2** [comment]
@Parham75 As has been said earlier in this issue thread, that error would indicate that your region setting in your profile does not match the region of your NNID. Did you make a new NNID after changing your region?

**Comment by MechanicalDragon0687** [comment]
Reading through the region change guide, it states that the process will unlink the NNID. If the process is not automatically unlinking the NNID, it would be a good idea to add those steps to ensure this issue doesnt happen.
If unlinking is not the only step, but creating a new NNID is required, this should also be part of the steps, imo.  

Thoughts?

**Comment by rufeef** [comment]
Anyone solved this problem yet?? I have searched (i think) the entire community about the "region changed console and accessing the eshop" and i haven't got the solution:( pleasee help:(

**Comment by Linguardium** [comment]
its not a problem to be solved. the warnings are clear in the guide. region change will (almost) always break eshop access.
